# Site/SEO settings
email: nadianicolaulima@gmail.com
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Nadia Nicolau
title: Nadia Nicolau
description: >
  Nadia Nicolau é fotografa e cineasta, e atualmente vive em Belo Horizonte.
url: http://nadia.github.io
twitter_username: NadiaNicolau1
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: https://twitter.com/NadiaNicolau1
  - name: instagram
    url: https://www.instagram.com/nadianicolau/
  - name: linkedin
    url: https://www.linkedin.com/in/nadia-nicolau-04258933/
  - name: github
    url: https://github.com/nadianicolau
  - name: facebook
    url: https://facebook.com/nadianicolau

# Contact settings
contact_img: /assets/images/placeholder-9.jpg
formcarry: https://formcarry.com/s/u3c9voAVGdq

# Disqus settings
disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Nadia Nicolau
    bio: Nadia Nicolau nasceu em Buenos Aires, atualmente se dedica a fotografia e ao cinema, na cidade de Belo horizonte é representante do Midia Ninja. E tem realizado diversas coberturas na America latina.
    url: nadia.github.io

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'Nadia Nicolau'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
